// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS1kasExIpREPONXnwRoegMHEg-z2bmeM',
    appId: '1:645446013229:web:e0fa376c4ffaccbaaf03a4',
    messagingSenderId: '645446013229',
    projectId: 'inventory-management-6ae0f',
    authDomain: 'inventory-management-6ae0f.firebaseapp.com',
    storageBucket: 'inventory-management-6ae0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfH9BsJJGAZkDSJacLa36u6cUyFhh7ssk',
    appId: '1:645446013229:android:d2a7ea6981e6f1b7af03a4',
    messagingSenderId: '645446013229',
    projectId: 'inventory-management-6ae0f',
    storageBucket: 'inventory-management-6ae0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpdzXcb_-ELQKcEI4O0zqYxR6MmXm6PHY',
    appId: '1:645446013229:ios:2f0c8e242bb5f87caf03a4',
    messagingSenderId: '645446013229',
    projectId: 'inventory-management-6ae0f',
    storageBucket: 'inventory-management-6ae0f.appspot.com',
    iosClientId: '645446013229-4th22kfb00ja0orrotgp0a4amt1aipjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.employedViewPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpdzXcb_-ELQKcEI4O0zqYxR6MmXm6PHY',
    appId: '1:645446013229:ios:2f0c8e242bb5f87caf03a4',
    messagingSenderId: '645446013229',
    projectId: 'inventory-management-6ae0f',
    storageBucket: 'inventory-management-6ae0f.appspot.com',
    iosClientId: '645446013229-4th22kfb00ja0orrotgp0a4amt1aipjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.employedViewPage',
  );
}
